version: '3'
services:
  scraper:
    image: sunandanbose/scraper
    ports:
        - 9000:9000
    volumes:
        - stocks-vol:/root/
  stocks-backend:
    image: sunandanbose/stocks-backend
    ports:
        - 8081:8081
    volumes:
        - stocks-vol:/root/
volumes:
  stocks-vol: 
      driver: local